apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-02-10T04:12:09Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: zomato
  name: zomato-lb
  namespace: raham
  resourceVersion: "1687"
  uid: 4d518240-58ee-437e-87ea-334478543de3
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 100.65.218.206
  clusterIPs:
  - 100.65.218.206
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31941
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: zomato
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a4d51824058ee437e87ea334478543de-864263588.ap-south-1.elb.amazonaws.com
